import = [
  "~/.config/alacritty/themes/themes/dario.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_material.toml"
]
shell = "zsh"
[font]
# normal  = {family = "CaskaydiaMono Nerd Font Mono", style = "Regular"}
# size = 7
# normal  = {family = "CommitMono Nerd Font Mono", style = "Regular"}
# size = 7
#  normal = {family = "RobotoMono Nerd Font", style = "Medium"}
# size = 6.5
normal = { family = "Spleen 6x12", style = "Regular"}
size = 8.5
# normal = { family = "Fragment Mono", style = "Regular" }  
# normal = { family = "KlartextMono", style = "Medium" }  
# size = 8
# normal = { family = "JetBrainsMono Nerd Font Mono", style = "Medium" }  
# size = 6.5
# normal = { family = "ASM-Regular", style = "Bold" }  
# size = 7
# normal = { family = "0xProto Nerd Font", style = "Regular" }  
# size = 7
# normal = { family = "MartianMono NFM", style = "Condensed Regular" }  
# size = 7.2
# normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }  
# size = 7
# normal = { family = "Noto Sans Mono", style = "Condensed Regular" }  
# size = 7.5
# offset = { x = 0, y = 0}

# normal = { family = "GeistMono Nerd Font", style = "Medium" }  
# normal = { family = "Terminess Nerd Font Mono", style = "Regular" }  
# size = 8
# offset = { x = 0, y = -3}
# normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" } 
# size = 8
# glyph_offset = { x = 0, y = 3 }
  
# size = 9.5
[window]
  # opacity =  0.95 #default
  opacity =  0.85
 # opacity =  1.0
  decorations = "Full"
# padding = { x = 20, y = 20 }
padding = { x = 15, y = 20 } #for Martian
# padding = { x = 10, y = 10 }
# padding = { x = 20, y = 40 }

